export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const ADDRESS_INFO_UPDATED = 'ADDRESS_INFO_UPDATED';
export const IMAGE_UPLOAD_BEGIN = 'IMAGE_UPLOAD_BEGIN';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const POSTCARD_PREVIEW_RECEIVED = 'POSTCARD_PREVIEW_RECEIVED';
export const POSTCARD_PREVIEW_ERROR = 'POSTCARD_PREVIEW_ERROR';
export const FETCHING_POSTCARD_PREVIEW = 'FETCHING_POSTCARD_PREVIEW';
