export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const ADDRESS_INFO_UPDATED = 'ADDRESS_INFO_UPDATED';
export const IMAGE_UPLOAD_BEGIN = 'IMAGE_UPLOAD_BEGIN';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const POSTCARD_PREVIEW_RECEIVED = 'POSTCARD_PREVIEW_RECEIVED';
export const POSTCARD_PREVIEW_ERROR = 'POSTCARD_PREVIEW_ERROR';
export const FETCHING_POSTCARD_PREVIEW = 'FETCHING_POSTCARD_PREVIEW';
export const FONT_UPDATED = 'FONT_UPDATED';
export const FONT_SIZE_UPDATED = 'FONT_SIZE_UPDATED';
export const ALIGNMENT_UPDATED = 'ALIGNMENT_UPDATED';
export const ADD_TO_ADDRESS = 'ADD_TO_ADDRESS';
export const REMOVE_TO_ADDRESS = 'REMOVE_TO_ADDRESS';
export const RESET_PREVIEW_STATE = 'RESET_PREVIEW_STATE';
export const ADD_SELECTED_ADDRESSES_TO_POSTCARD = 'ADD_SELECTED_ADDRESSES_TO_POSTCARD';
export const SET_FROM_ADDRESS = 'SET_FROM_ADDRESS';

// address book
export const SHOW_ADDRESS_BOOK = 'SHOW_ADDRESS_BOOK';
export const TOGGLE_ADDRESS_BOOK_ADDRESS_SELECTED = 'TOGGLE_ADDRESS_BOOK_ADDRESS_SELECTED';
export const UPDATE_ADDRESS_SEARCH = 'UPDATE_ADDRESS_SEARCH';
export const NEW_ADDRESS_SAVED = 'NEW_ADDRESS_SAVED';
export const SHOW_CREATE_NEW_ADDRESS = 'SHOW_CREATE_NEW_ADDRESS';
export const HIDE_ADDRESS_BOOK = 'HIDE_ADDRESS_BOOK';
export const FETCH_ADDRESS_BOOK_ADDRESSES_SUCCESS = 'FETCH_ADDRESS_BOOK_ADDRESSES_SUCCESS';
export const NEW_ADDRESS_SAVE_ERROR = 'NEW_ADDRESS_SAVE_ERROR';
