export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const ADDRESS_INFO_UPDATED = 'ADDRESS_INFO_UPDATED';
export const IMAGE_UPLOAD_BEGIN = 'IMAGE_UPLOAD_BEGIN';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE'
